epoch: 300

LearningRate0:
  base_lr: 0.01
  schedulers:
  - !YOLOXCosineDecay
    max_epochs: 150
    no_aug_epochs: 10
    min_lr_ratio: 0.05
  - !ExpWarmup
    start_lr: 0.
    warmup_epochs: 3

LearningRate:
  base_lr: 0.01
  schedulers:
  - !YOLOXCosineDecay
    max_epochs: 150
    no_aug_epochs: 10
    min_lr_ratio: 0.05
  - !ExpWarmup
    start_lr: 0.
    warmup_epochs: 3

OptimizerBuilder:
  optimizer:
    type: "Momentum"
    momentum: 0.937
    use_nesterov: True
    param_groups:
      - params: ['bias', 'bn']
        weight_decay: 0.0
  regularizer:
    factor: 0.0005
    type: L2
