architecture: YOLOv3
use_ema: True
ema_decay: 0.9998
act: silu
#find_unused_parameters: True

depth_factor: 0.33
width_factor: 0.50

YOLOv3:
  backbone: CSPDarkNet
  neck: YOLOCSPPAN
  yolo_head: YOLOv3Head
  post_process: YOLOv5PostProcess

CSPDarkNet:
  arch: "P5"
  return_idx: [2, 3, 4]

YOLOCSPPAN:
  depthwise: false

YOLOv3Head:
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv5Loss

YOLOv5Loss:
  balance: [4.0, 1.0, 0.4]
  box_weight: 0.05
  obj_weight: 1.0
  cls_weght: 0.5

YOLOv5PostProcess:
  decode:
    name: YOLOv5Box
    conf_thresh: 0.001
    downsample_ratio: 32
  nms:
    name: MultiClassNMS
    keep_top_k: 1000
    score_threshold: 0.001
    nms_threshold: 0.65
    nms_top_k: 30000
    return_index: true
