architecture: YOLOv3
norm_type: sync_bn
use_ema: True
ema_decay: 0.9999
ema_decay_type: "exponential"
act: silu
find_unused_parameters: True

depth_factor: 0.33
width_factor: 0.50

YOLOv3:
  backbone: CSPDarkNet
  neck: YOLOCSPPAN
  yolo_head: YOLOv5Head
  post_process: ~

CSPDarkNet:
  arch: "P5"
  return_idx: [2, 3, 4]

YOLOCSPPAN:
  depthwise: false

YOLOv5Head:
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  anchor_masks: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
  loss: YOLOv5Loss
  nms:
    name: MultiClassNMS
    keep_top_k: 300
    score_threshold: 0.001
    nms_threshold: 0.65
    nms_top_k: 30000
